#!/usr/bin/env python3
"""Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""


def calculate_sum_of_even_fibbonacci_numbers(max_value: int) -> int:
    print(f"Calculating sum of even Fibonacci numbers until {max_value}.")
    fibbonacci_sequence = [1, 2]
    while fibbonacci_sequence[-1] < max_value:
        fibbonacci_sequence.append(fibbonacci_sequence[-1] + fibbonacci_sequence[-2])
    return sum(fibbonacci_sequence[1::3])


if __name__ == "__main__":
    print(f"Solution: {calculate_sum_of_even_fibbonacci_numbers(max_value=int(4e6))}")
